openapi: 3.0.1
info:
  title: Redeem API
  version: 'v1'

paths:
  /api/v1/redeems:
    post:
      summary: 'Create a new redeem'
      description: 'Creates a new redeem associated with a redeem page, user, and address, including optional size options and answers for questions.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                redeem:
                  type: object
                  properties:
                    redeem_page_id:
                      type: integer
                      description: 'ID of the redeem page'
                      example: 2
                    size_option_id:
                      type: integer
                      description: 'ID of the size option (if applicable)'
                      example: 1
                    user:
                      type: object
                      description: 'User details for the redeem'
                      properties:
                        name:
                          type: string
                          example: 'Rebeca Rodrigues Sousa'
                        registration_number:
                          type: string
                          example: '88463540015'
                        email:
                          type: string
                          example: 'rebeca@email.com'
                    address:
                      type: object
                      description: 'Address details for the redeem'
                      properties:
                        street:
                          type: string
                          example: 'Rua Beija-Flor'
                        number:
                          type: string
                          example: '1246'
                        complement:
                          type: string
                          example: 'Apt 4'
                        neighborhood:
                          type: string
                          example: 'Alvarenga'
                        city:
                          type: string
                          example: 'São Bernardo do Campo'
                        state:
                          type: string
                          example: 'SP'
                        zip_code:
                          type: string
                          example: '09856150'
                        country:
                          type: string
                          example: 'Brazil'
                    answers:
                      type: array
                      description: 'Answers to questions for the redeem page'
                      items:
                        type: object
                        properties:
                          content:
                            type: string
                            example: 'Azul'
                          question_id:
                            type: integer
                            example: 1
      responses:
        '201':
          description: 'Redeem successfully created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                    enum: ['pending', 'approved', 'rejected']
                  redeem_page_id:
                    type: integer
                  size_option_id:
                    type: integer
                  user:
                    $ref: '#/components/schemas/User'
                  address:
                    $ref: '#/components/schemas/Address'
                  answers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
                        question_id:
                          type: integer
        '422':
          description: 'Unprocessable Entity - Validation errors'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        registration_number:
          type: string
        email:
          type: string
    Address:
      type: object
      properties:
        street:
          type: string
        number:
          type: string
        complement:
          type: string
        neighborhood:
          type: string
        city:
          type: string
        state:
          type: string
        zip_code:
          type: string
        country:
          type: string
